spring:
  application:
    name: employee-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/employeedb

  security:
    user:
      name: admin
      password: admin123

  cache:
    type: caffeine
    cache-names:
      - employees
    caffeine:
      spec: maximumSize=10,expireAfterWrite=10m



server:
  port: 8080

logging:
  file:
    name: logs/employee-service.log

  level:
    root: INFO

